baseURL = 'https://LiuShuoJiang.github.io'
languageCode = 'en-us'
title = "Shuojiang Liu's Personal Website"
theme = "hugo-theme-relearn-5122"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  mathJaxInitialize = "{ \"chtml\": { \"displayAlign\": \"left\" } }"
  themeVariant = [ "auto", "blue" ]

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Math codefences
    guessSyntax = false

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repository"
identifier = "ds"
url = "https://github.com/LiuShuoJiang"
weight = 10
