baseURL = 'https://LiuShuoJiang.github.io'
languageCode = 'en-us'
title = "Shuojiang Liu's Personal Website"
theme = "hugo-theme-relearn-5230"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  mathJaxInitialize = "{ \"chtml\": { \"displayAlign\": \"left\" } }"
  themeVariant = [ "auto", "relearn-bright" ]
  themeVariantAuto = [ "relearn-bright", "neon" ]

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Math codefences
    guessSyntax = false

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Repository"
identifier = "ds"
url = "https://github.com/LiuShuoJiang"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> LinkedIn"
url = "https://www.linkedin.com/in/shuojiang-liu-09a749260/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Hugging Face"
url = "https://huggingface.co/shuojiang"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> XJTU AI"
url = "https://huggingface.co/XJTU-AI"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-tags'></i> Algorithm Notes"
url = "https://github.com/LiuShuoJiang/algorithm-notes"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-tags'></i> Numerical Notes"
url = "https://liushuojiang.github.io/Numerical-Linear-Algebra/"
weight = 40

[markup.goldmark.renderer]
  unsafe = true
